# Generated by Django 4.1.4 on 2022-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_number', models.IntegerField()),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orderid',
            fields=[
                ('ordernumber', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
