# Generated by Django 4.1.4 on 2022-12-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0003_orderid_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish_price',
        ),
        migrations.RemoveField(
            model_name='orderid',
            name='total',
        ),
    ]
