# Generated by Django 4.1.4 on 2022-12-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0004_remove_menu_dish_price_remove_orderid_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderid',
            old_name='variable',
            new_name='fooditem',
        ),
    ]
