# Generated by Django 4.1.4 on 2022-12-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0005_rename_variable_orderid_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='order_status',
            field=models.CharField(choices=[('Progressing', 'Progressing'), ('Prepared', 'Prepared'), ('Completed', 'Completed')], default='Progressing', max_length=100),
        ),
    ]
